// mockProducts.js

const mockProducts = [
  {
    id: 1,
    image: "/assets/article1.jpeg",
    title: "Modern Living Room Set",
    price: 899.99,
    oldPrice: 1099.99,
    rating: 4.8,
    category: "Furniture",
    description: "A cozy and elegant living room setup for a modern home.",
    dateAdded: "2023-10-01",
    sales: 150,
  },
  {
    id: 2,
    image: "/assets/article2.jpeg",
    title: "Kitchen Island Set",
    price: 799.99,
    oldPrice: 999.99,
    rating: 4.7,
    category: "Furniture",
    description: "Stylish and functional kitchen island with bar stools.",
    dateAdded: "2023-09-15",
    sales: 200,
  },
  {
    id: 3,
    image: "/assets/article3.jpeg",
    title: "Home Office Workspace",
    price: 649.99,
    oldPrice: 849.99,
    rating: 4.6,
    category: "Furniture",
    description: "An ergonomic and compact home office setup.",
    dateAdded: "2023-08-10",
    sales: 180,
  },
  {
    id: 4,
    image: "/assets/red-table.png",
    title: "Red Accent Table",
    price: 59.99,
    oldPrice: null,
    rating: 4.3,
    category: "Furniture",
    description: "A bold red accent table to add flair to any room.",
    dateAdded: "2023-07-20",
    sales: 90,
  },
  {
    id: 5,
    image: "/assets/tall-lamp.png",
    title: "Tall Standing Lamp",
    price: 119.99,
    oldPrice: 149.99,
    rating: 4.5,
    category: "Decor",
    description: "Elegant and modern standing lamp with warm lighting.",
    dateAdded: "2023-09-05",
    sales: 130,
  },
  {
    id: 6,
    image: "/assets/couch-gray.png",
    title: "Gray Fabric Couch",
    price: 499.99,
    oldPrice: 699.99,
    rating: 4.7,
    category: "Furniture",
    description: "Comfortable and stylish gray fabric couch for your living room.",
    dateAdded: "2023-10-05",
    sales: 170,
  },
  {
    id: 7,
    image: "/assets/black-table.png",
    title: "Black Coffee Table",
    price: 129.99,
    oldPrice: 159.99,
    rating: 4.4,
    category: "Furniture",
    description: "Minimalist black coffee table for a modern touch.",
    dateAdded: "2023-08-25",
    sales: 110,
  },
  {
    id: 8,
    image: "/assets/toast.png",
    title: "Retro Toaster",
    price: 49.99,
    oldPrice: 69.99,
    rating: 4.2,
    category: "Kitchen",
    description: "A stylish and functional retro toaster for your kitchen.",
    dateAdded: "2023-07-15",
    sales: 80,
  },
];

export default mockProducts;
