const mockProducts = [
  {
    id: 1,
    image: "https://images.pexels.com/photos/1099816/pexels-photo-1099816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Contemporary Sofa Set",
    price: 1199.99,
    oldPrice: 1399.99,
    rating: 4.9,
    category: "Furniture",
    description:
      "Luxurious and spacious sofa set that elevates your living room's comfort and style. This sofa set features plush cushioning, high-quality upholstery, and a modern design, making it a perfect choice for hosting guests or relaxing with family. Designed for both aesthetics and durability, it's an excellent addition to any home.",
    dateAdded: "2023-10-20",
    sales: 210,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1090638/pexels-photo-1090638.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Marble Dining Table",
    price: 899.99,
    oldPrice: 1199.99,
    rating: 4.8,
    category: "Furniture",
    description:
      "Elegant marble dining table that adds a touch of sophistication to any dining area. With a polished marble surface and sturdy base, this table is built to last while offering a timeless appeal. Perfect for family meals or hosting special occasions, it's a blend of beauty and functionality.",
    dateAdded: "2023-09-28",
    sales: 300,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Ergonomic Office Chair",
    price: 299.99,
    oldPrice: 399.99,
    rating: 4.7,
    category: "Office",
    description:
      "Comfortable ergonomic office chair designed to support long working hours. With adjustable height, reclining features, and breathable mesh material, this chair ensures optimal posture and minimizes back pain. A must-have for professionals seeking comfort and productivity.",
    dateAdded: "2023-08-18",
    sales: 250,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/298842/pexels-photo-298842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Minimalist Coffee Table",
    price: 199.99,
    oldPrice: 249.99,
    rating: 4.6,
    category: "Furniture",
    description:
      "Sleek and modern coffee table to complement your living space. Its minimalist design and durable build make it an ideal centerpiece for your living room. With ample space for beverages, books, and decor, it blends practicality with style effortlessly.",
    dateAdded: "2023-10-01",
    sales: 180,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/4112237/pexels-photo-4112237.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "LED Standing Lamp",
    price: 89.99,
    oldPrice: 109.99,
    rating: 4.5,
    category: "Decor",
    description:
      "Energy-efficient LED lamp with adjustable brightness to suit any mood or occasion. Its sleek and modern design enhances your decor, while its adjustable height and dimmable light make it perfect for reading, working, or relaxing in any room.",
    dateAdded: "2023-09-12",
    sales: 160,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/4440220/pexels-photo-4440220.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Mid-Century Armchair",
    price: 549.99,
    oldPrice: 699.99,
    rating: 4.8,
    category: "Furniture",
    description:
      "Stylish mid-century armchair with plush cushioning that offers both comfort and elegance. Its versatile design fits seamlessly into modern, traditional, or eclectic interiors, making it a standout addition to any room.",
    dateAdded: "2023-10-15",
    sales: 220,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Wooden Bookshelf",
    price: 399.99,
    oldPrice: null,
    rating: 4.7,
    category: "Furniture",
    description:
      "Spacious and sturdy wooden bookshelf ideal for home or office use. Designed with multiple shelves for books, decor, or personal items, this bookshelf is both functional and aesthetically pleasing, fitting seamlessly into any interior style.",
    dateAdded: "2023-08-10",
    sales: 140,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Stainless Steel Kettle",
    price: 59.99,
    oldPrice: 79.99,
    rating: 4.3,
    category: "Kitchen",
    description:
      "Durable stainless steel kettle with a quick boil feature that makes brewing tea or coffee fast and convenient. Its sleek design, comfortable handle, and easy-to-clean interior make it an essential kitchen appliance.",
    dateAdded: "2023-07-22",
    sales: 120,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/1510173/pexels-photo-1510173.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "High-Performance Blender",
    price: 299.99,
    oldPrice: 349.99,
    rating: 4.9,
    category: "Kitchen",
    description:
      "Blend smoothies, soups, and sauces effortlessly with this high-performance blender. Its powerful motor and durable blades make it an essential kitchen tool for healthy cooking.",
    dateAdded: "2023-10-15",
    sales: 250,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/1484981/pexels-photo-1484981.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Wireless Noise-Canceling Headphones",
    price: 249.99,
    oldPrice: 299.99,
    rating: 4.8,
    category: "Electronics",
    description:
      "Immerse yourself in high-quality sound with these wireless noise-canceling headphones. Designed for comfort and long listening sessions, they deliver an unmatched audio experience.",
    dateAdded: "2023-09-28",
    sales: 320,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/1648776/pexels-photo-1648776.jpeg",
    title: "Adjustable Standing Desk",
    price: 599.99,
    oldPrice: 749.99,
    rating: 4.7,
    category: "Office",
    description:
      "Promote better posture and productivity with this adjustable standing desk. Its ergonomic design allows you to switch between sitting and standing effortlessly, making it ideal for home or office use.",
    dateAdded: "2023-08-20",
    sales: 200,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Stainless Steel Cookware Set",
    price: 349.99,
    oldPrice: 399.99,
    rating: 4.9,
    category: "Kitchen",
    description:
      "Upgrade your kitchen with this premium stainless steel cookware set. Built to last and easy to clean, it offers superior heat distribution and compatibility with all stovetops.",
    dateAdded: "2023-11-05",
    sales: 260,
  },
  {
    id: 13,
    image: "https://images.pexels.com/photos/1228483/pexels-photo-1228483.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Eco-Friendly Bamboo Bedding Set",
    price: 179.99,
    oldPrice: 219.99,
    rating: 4.8,
    category: "Bedroom",
    description:
      "Sleep soundly with this eco-friendly bamboo bedding set. Naturally hypoallergenic and breathable, it provides a soft, luxurious feel while being gentle on the environment.",
    dateAdded: "2023-10-22",
    sales: 190,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/1571458/pexels-photo-1571458.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Modern Wall Clock",
    price: 69.99,
    oldPrice: 89.99,
    rating: 4.5,
    category: "Home Decor",
    description:
      "Enhance your home's decor with this sleek and modern wall clock. Its minimalist design and durable build make it a perfect addition to any room.",
    dateAdded: "2023-09-18",
    sales: 150,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/2079436/pexels-photo-2079436.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Professional DSLR Camera",
    price: 1299.99,
    oldPrice: 1499.99,
    rating: 4.9,
    category: "Electronics",
    description:
      "Capture stunning photos and videos with this professional-grade DSLR camera. Equipped with advanced features and interchangeable lenses, it’s perfect for both beginners and seasoned photographers.",
    dateAdded: "2023-08-30",
    sales: 310,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/1239298/pexels-photo-1239298.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Compact Home Treadmill",
    price: 899.99,
    oldPrice: 999.99,
    rating: 4.6,
    category: "Fitness",
    description:
      "Stay active from the comfort of your home with this compact treadmill. Featuring multiple speed settings and a foldable design, it's perfect for small spaces and fitness enthusiasts alike.",
    dateAdded: "2023-07-15",
    sales: 220,
  },
  {
    id: 17,
    image: "https://images.pexels.com/photos/271795/pexels-photo-271795.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Electric Adjustable Bed Frame",
    price: 1099.99,
    oldPrice: 1299.99,
    rating: 4.7,
    category: "Bedroom",
    description:
      "Transform your sleep experience with this electric adjustable bed frame. Designed for maximum comfort and convenience, it features customizable settings to meet your unique needs.",
    dateAdded: "2023-10-08",
    sales: 180,
  },
];





export default mockProducts;
